version: "3.8"
services:

    #php
    php:
      build: 
        context: .
        target: php
        args:
          - APP_ENV=${APP_ENV}
      working_dir: /var/www
      volumes:
        - ./:/var/www
      ports:
        - 8000:8000
      environment:
        - APP_ENV=${APP_ENV}
        - CONTAINER_ROLE=app
      depends_on:
        - database

    #Database Server
    database:
      image: mysql:8.0
      ports:
          -   3306:3306
      environment:
          - MYSQL_DATABASE=${DB_DATABASE}
          - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
          - MYSQL_ALLOW_EMPTY_PASSWORD=true
      volumes:
          - db-data:/var/lib/mysql

    node:
      build: 
        context: .
        target: node
      volumes:
        - .:/usr/src
        - ./node_modules:/usr/src/node_modules
        - ./storage/app/public:/var/www/html/public/storage
      tty: true

volumes:
    db-data: ~
